-- MySQL Script generated by MySQL Workbench
-- Mon Apr 17 14:06:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
DROP DATABASE BDIntegradoeTablas;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDIntegradorTablas` DEFAULT CHARACTER SET utf8mb4 ;
USE `BDIntegradorTablas` ;

-- -----------------------------------------------------
-- Table `mydb`.`resultados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDIntegradorTablas`.`resultados` ;

CREATE TABLE IF NOT EXISTS `BDIntegradorTablas`.`resultados` (
  `fase` INT NOT NULL,
  `partido` INT NOT NULL,
  `equipo1` VARCHAR(45) NOT NULL,
  `golEquipo1` INT NOT NULL,
  `golEquipo2` INT NOT NULL,
  `equipo2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`partido`))
ENGINE = InnoDB;
desc resultados;
desc pronosticos;
SHOW TABLES FROM BDIntegradorTablas;

-- -----------------------------------------------------
-- Table `mydb`.`pronosticos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDIntegradorTablas`.`pronosticos` ;

CREATE TABLE IF NOT EXISTS `BDIntegradorTablas`.`pronosticos` (
  `idparticipante` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `partido` INT NOT NULL,
  `equipo1` VARCHAR(45) NOT NULL,
  `golEquipo1` INT NOT NULL,
  `golEquipo2` INT NOT NULL,
  `equipo2` VARCHAR(45) NOT NULL,
  INDEX `partido_idx` (`partido` ASC) VISIBLE,
  CONSTRAINT `partido`
    FOREIGN KEY (`partido`)
    REFERENCES `BDIntegradorTablas`.`resultados` (`partido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SHOW VARIABLES LIKE 'secure_file_priv';
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/resultados - Hoja 2.csv'
INTO TABLE resultados
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SHOW VARIABLES LIKE 'secure_file_priv';
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/pronosticos - Hoja 1 (1).csv'
INTO TABLE pronosticos
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

select * from resultados;
select * from pronosticos;
