-- MySQL Script generated by MySQL Workbench
-- Wed Apr 12 20:00:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Qatar2022
-- -----------------------------------------------------
-- CREE LA BASE DE DATOS APARTIR DEL MODELO MYSQL Y ME AHORRE ESTOS PASO AL EXECUTAR LAS LINEAS SIGUIENTES
-- verifico que se no exista la bases de datos
-- show databases;
-- creo base de dato
-- Creo clave primaria y la hago autoincremental
-- alter table empleado add primary key (IdEmpleado);
-- Clave primaria: la hago autoincremental
-- alter table empleado modify IdEmpleado int auto_increment;


DROP SCHEMA IF EXISTS `Qatar2022` ;
-- -----------------------------------------------------
-- Schema Qatar2022
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Qatar2022` DEFAULT CHARACTER SET utf8mb4;
USE `Qatar2022` ;
-- -----------------------------------------------------
-- Table `Qatar2022`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Qatar2022`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `Qatar2022`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `Departamento` VARCHAR(45) NOT NULL,
  `Presupuesto` INT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Qatar2022`.`Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Qatar2022`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `Qatar2022`.`Empleados` (
  `idempleados` INT NOT NULL AUTO_INCREMENT,
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Apellido` VARCHAR(60) NOT NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idempleados`),
  CONSTRAINT `fk_Empleados_Departamento`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `Qatar2022`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Empleados_Departamento_idx` ON `Qatar2022`.`Empleados` (`Departamento_idDepartamento` ASC) VISIBLE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ****************************************************************** --
--   DDL : Lenguaje de Definicón de Datos
-- ****************************************************************** --

-- verifico que se creo la bd correctamente
show databases;

-- entro a la base de datos creada para poder crear las tablas
use Qatar2022; 

-- controlo que se haya creado bien la tabla
show tables; 

-- Veo los campos dentro de la tabla        
desc departamento;       
desc empleados;   


-- ****************************************************************** --
--   DML-DQL : Lenguaje de Manipulación y Consulta de Datos 
-- ****************************************************************** --

-- Insertamos datos a la table, hay que respetar la definicion de los campos
INSERT INTO departamento (departamento,presupuesto)
VALUES('sistemas',100000);
INSERT INTO departamento (departamento,presupuesto)
VALUES('mantenimiento',20000);
INSERT INTO departamento (departamento,presupuesto)
VALUES('logistica',2000000);
INSERT INTO departamento (departamento,presupuesto)
VALUES('dev java',250000);
INSERT INTO departamento (departamento,presupuesto)
VALUES('testing',30000);


INSERT INTO empleados (DNI,nombre,apellido,nacionalidad,Departamento,Departamento_idDepartamento)
VALUES(99888777,'Lionel Andrés','Messi','Argentino','sistemas',1);

INSERT INTO empleados (DNI,nombre,apellido,nacionalidad,Departamento,Departamento_idDepartamento)
VALUES(11222333,'Emiliano','Martinez','Argentino','mantenimiento',2);

INSERT INTO empleados (DNI,nombre,apellido,nacionalidad,Departamento,Departamento_idDepartamento)
VALUES(44555666,'Enzo','Perez','Argentino','logistica',3);

INSERT INTO empleados (DNI,nombre,apellido,nacionalidad,Departamento,Departamento_idDepartamento)
VALUES(44555666,'Diego','Ramiro','Argentino','dev java',4);

INSERT INTO empleados (DNI,nombre,apellido,nacionalidad,Departamento,Departamento_idDepartamento)
VALUES(34555566,'Juancito Mengano','Fulano','Argentino','testing',5);

-- Seleccionamos y mostramos todos(*) los datos de la tabla 
select * from empleados;
select * from departamento;
-- Seleccionamos una fila de la tabla con where
select * from empleados where departamento= 'sistemas';

-- Seleccionamos fila y algunas columnas tabla con where
select  departamento, apellido, nombre as Nombre from empleados where departamento= 'logistica';

-- Seleccionamos fila y algunas columnas tabla con where , concateno Ap y Nombre

select  departamento, CONCAT_WS(', ',apellido,nombre) as Nombre from empleados where departamento= 'logistica';

-- Seleccionamos fila y algunas columnas tabla con where
select  * from empleados where apellido= 'Messi';

-- Modifico las columnas DNI, Nombre, Apellido y Depto la fila cuyo IdEmpleado es 4
UPDATE empleados SET DNI = 40229235, nombre = 'Manuel', apellido = 'Martino'
WHERE IdEmpleados = 4;

-- Elimino fila repetida IdEmpleado = 5
delete from empleados where IdEmpleados = 5;


-- ****************************************************************** --
-- Sentecias utiles pero peligrosas
-- ****************************************************************** --
-- create database cursojava; use cursojava; create table t1(dato int);
-- alter table t1 rename t2;
-- drop table t2;
-- DROP DATABASE IF EXISTS argentina2023;
-- ****************************************************************** --
